# Use an official Python image
FROM python:3.10.0

# Set working directory
WORKDIR .

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files
COPY . .

# Expose the port FastAPI will run on
EXPOSE 8000

# Run uvicorn automatically when the container starts
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]